---
users:
- name: fred
  ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICn2jLmrDKYwt1zouEjyAwdItBJ2A2MyULwLr1IbF5rz"
  state: present
- name: mark
  ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBQh0DIHOIs4ZBok6F8I2JmZGcdu6NPS8R7cY5ndQaID"
  state: present
- name: adam
  ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPY89d+z8ZjNPuqNUJ/Ny3X4PxDGz1LAWzSeMWBD1iwG"
  state: present

packages:
  postgresql:
    Centos: "postgres-server"
    Ubuntu: "postgresql"
  docker:
    Centos: "docker"
    Ubuntu: "docker.io"
  pip:
    Centos: "pip"
    Ubuntu: "python-pip"
  python_docker:
    Centos: "docker-py"
    Ubuntu: "docker-py"
