---
- name: add docker repository
  command:
    cmd: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
    creates: /etc/yum.repos.d/docker-ce.repo
  when: ansible_distribution == "CentOS"

- name: install docker package
  package:
    name: "{{item}}"
    state: latest
  loop: "{{env.packages.docker[ansible_distribution]}}"
  notify: docker started
  tags:
  - packages
  - docker

- name: install python docker SDK via pip
  pip:
    name: "docker-py"
    state: present
